#!/bin/bash

VOLUME=$(pamixer --get-volume-human | tr -d '%')

function icon() {
  if [[ $VOLUME -ge 70 ]]; then
    echo ''
  elif [[ $VOLUME -ge 25 ]]; then
    echo ''
  elif [[ $VOLUME -ge 1 ]]; then
    echo ''
  else
    echo ''
  fi
}

ICON=$(icon)
echo '{"volume": "'$VOLUME'", "icon": "'$ICON'"}'

pactl subscribe | rg --line-buffered "on sink" | while read -r _; do
  VOLUME=$(pamixer --get-volume-human | tr -d '%')
  ICON=$(icon)
  echo '{"volume": "'$VOLUME'", "icon": "'$ICON'"}'
done
